apiVersion: v1
kind: Pod
metadata:
  name: rappor-lab-fixture
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: fixture
      image: scratch
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
